name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: testdb
      PGPORT: 5432
      JWT_SECRET: "githubactionssecret"
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Wait for Postgres
      run: |
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 && break
          sleep 1
        done
    - name: Create users table
      run: |
        psql -h localhost -U postgres -d testdb -c "
          CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100),
            email VARCHAR(100) UNIQUE,
            age INTEGER,
            password VARCHAR(200),
            role VARCHAR(20) DEFAULT 'user',
            refresh_token TEXT
          );
        "
    - name: Run seed script
      run: npm run seed
    - name: Run tests
      run: npm test